### ISSUE TITLE
Allow an admin to change user properties without password

### ISSUE THREAD

**Issue by mrnfrancesco** [pwndoc-ng/pwndoc-ng#90]
Right now it is not possible for an admin to change user's properties without changing its password too.
In some cases, as an admin, I'd like to just disable/enable an account or change its role without having to change its password.

**Comment by Zeecka** [comment]
Fixed #109 (it was just a front-end issue)

**Comment by CassioN** [comment]
I'm still not able to change an user's property without changing its password too.

![image](https://github.com/user-attachments/assets/ce3e8057-1fab-4011-9fc6-81d482a34f52)

For what I've seen, I have the #109 implemented.

![image](https://github.com/user-attachments/assets/a02ee438-d116-4eaf-8363-cb3c5df5fdff)
